# Generated by Django 3.1.3 on 2021-05-28 06:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreJ', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Jugadores',
            },
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('jugadorB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadorB', to='aplicacion.jugador')),
                ('jugadorN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadorN', to='aplicacion.jugador')),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=4)),
                ('orden', models.IntegerField(default=0)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.jugador')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.partida')),
            ],
            options={
                'verbose_name_plural': 'Movimientos',
            },
        ),
    ]
